services:
  app:
    ports:
      - '80:80'
      - '443:443'
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_PUBLISHER_JWT_KEY}
      - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_SUBSCRIBER_JWT_KEY}
      - MERCURE_HUB_URL=${MERCURE_HUB_URL}
      - CHAT_DB_PATH=/data/chat.sqlite
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./server:/app/server
      - ./public:/app/landing
